name = "hubitat-proxy"
main = "worker.js"
compatibility_date = "2024-09-01"

[vars]
# Replace with your Maker API base (without trailing slash)
# Example: https://cloud.hubitat.com/api/<instance-id>/apps/<appId>
HUBITAT_BASE = "https://cloud.hubitat.com/api/e45cb756-9028-44c2-8a00-e6fb3651856c/apps/77"

# Add the token as a secret (do not put the token here):
# wrangler secret put HUBITAT_TOKEN

